import { test, expect } from '@playwright/test'
test.use({ viewport: { width: 1440, height: 1000 } })
test('alandalus gallery + map + icons', async ({ page }) => {
  await page.goto('/projects/alandalus', { waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(1500)
  const thumbs = await page.getByRole('button', { name: /^Фото \d/ }).count()
  const main = () => page.locator('div.bg-black > img').first().getAttribute('src')
  const a = await main()
  await page.getByRole('button', { name: 'Фото 3' }).first().click()
  await page.waitForTimeout(250)
  const b = await main()
  const map = await page.locator('iframe[src*="yandex"]').count()
  console.log('thumbs:', thumbs, '| gallery a-b:', a?.split('/').pop(), '->', b?.split('/').pop(), '| map:', map)
  expect(thumbs).toBe(4)
  expect(b).not.toBe(a)
  expect(map).toBeGreaterThan(0)
  const interior = page.locator('text=Скоростные лифты').locator('xpath=ancestor::section[1]')
  await interior.scrollIntoViewIfNeeded()
  await page.waitForTimeout(400)
  await interior.screenshot({ path: 'tests/shots/alandalus-interior.png' })
})
